// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ColorController from "./color_controller"
application.register("color", ColorController)

import ContactsFilterController from "./contacts_filter_controller"
application.register("contacts-filter", ContactsFilterController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)
